### PR TITLE
Update to official Arch Linux image

### PR DESCRIPTION
**Pull request by billyb2**

### CODE REVIEW

**Review by ponsfrilus — APPROVED** [review]
LGTM

**Comment by billyb2** [comment]
LGTM?

**Comment by ponsfrilus** [comment]
@billyb2 [LGTM](https://www.urbandictionary.com/define.php?term=LGTM).

**Comment by billyb2** [comment]
Oh, thank you.

**Comment by ponsfrilus** [comment]
> Oh, thank you.

You are welcome. Just choose between Let's get this merged or Looks good to me :)

**Pull request merged**
